version: "3.8"

services:
  backend:
    build:
      context: .
      target: backend
    env_file:
      - .env
    ports:
      - "${BACKEND_PORT:-5000}:5000"
    networks:
      - app-network
    container_name: backend
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  client:
    build:
      context: .
      target: client
    env_file:
      - .env
    ports:
      - "${CLIENT_PORT:-80}:80"
    networks:
      - app-network
    container_name: client
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  app-network:
    driver: bridge